backend:
  name: github
  repo: ebiwd/EBI-Corporatesite-Training # Path to your Github repository
  branch: master # Branch to update
  site_domain: designer-hare-16270.netlify.com # Your Netlify site address if different from host
media_folder: "static/images" # Media files will be stored in the repo under images/uploads
collections:
  - name: "modules" # Used in routes, e.g. /admin/collections/blog
    label: "Modules" # Used in the UI
    folder: "_posts/modules" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Group", name: "group", widget: "hidden", default: "module"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "hidden"}
      - {label: "Type", name: "type", widget: "string", default: "half day"}
      #- {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "New ('yes/no')", name: "new", widget: "string"}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Resources", name: "resources", widget: "markdown"}
      - {label: "Learning outcomes", name: "outcomes", widget: "markdown"}
      - {label: "Related resources/courses", name: "related", widget: "markdown"}
